//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMyWorldEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_Services
    {
        public Nullable<int> IdCategories { get; set; }
        public Nullable<int> IdServices { get; set; }
        public int Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Service Service { get; set; }
    }
}
