//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMyWorldEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_Cards
    {
        public int Id { get; set; }
        public decimal NumberCard { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
