//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMyWorldEC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyWorldECEntities1 : DbContext
    {
        public MyWorldECEntities1()
            : base("name=MyWorldECEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonus_Points> Bonus_Points { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Categories_Services> Categories_Services { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Children> Childrens { get; set; }
        public virtual DbSet<Discount_Cards> Discount_Cards { get; set; }
        public virtual DbSet<Entertainment_Centers> Entertainment_Centers { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Services_Entertainment_Centers> Services_Entertainment_Centers { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
