//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMyWorldEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Entertainment_Centers
    {
        public Nullable<int> ServiceId { get; set; }
        public int Id { get; set; }
        public Nullable<int> Entertainment_CenterId { get; set; }
    
        public virtual Entertainment_Centers Entertainment_Centers { get; set; }
        public virtual Service Service { get; set; }
    }
}
